export const posts = [
  {
    id: 1,
    category: 'Wig Guide',
    title: 'How to choose the right wig length for you',
    excerpt: 'From short bobs to long flowing layers, find a length that fits your style, face and everyday routine.',
    date: 'Sep 24, 2026',
    image: '/wig1.jpeg',
    featured: true,
  },
  {
    id: 2,
    category: 'Hair Care',
    title: 'How to keep your human hair wig looking fresh',
    excerpt: 'Simple habits that help your wig stay soft, clean and wearable for longer.',
    date: 'Sep 18, 2026',
    image: '/wig2.jpeg',
  },
  {
    id: 3,
    category: 'Installation',
    title: 'What to expect from a professional wig installation',
    excerpt: 'A simple look at the prep, fitting and styling process before your appointment.',
    date: 'Sep 12, 2026',
    image: '/wig3.jpeg',
  },
  {
    id: 4,
    category: 'Style',
    title: 'Straight, body wave or curls?',
    excerpt: 'Breaking down popular textures and the kind of look each one creates.',
    date: 'Sep 06, 2026',
    image: '/wig4.jpeg',
  },
  {
    id: 5,
    category: 'Wig Guide',
    title: '5 things to check before buying a wig',
    excerpt: 'Density, lace, length, cap size and texture. Know what you are paying for.',
    date: 'Aug 29, 2026',
    image: '/wig5.jpeg',
  },
  {
    id: 6,
    category: 'Trends',
    title: 'Wig styles we are loving right now',
    excerpt: 'A look at some of the styles currently making waves at Nywele.',
    date: 'Aug 21, 2026',
    image: '/wig6.jpeg',
  },
  {
    id: 7,
    category: 'Hair Care',
    title: 'Your wig deserves a proper wash day',
    excerpt: 'The right way to clean, condition and prepare your wig for its next wear.',
    date: 'Aug 15, 2026',
    image: '/wig7.jpeg',
  },
  {
    id: 8,
    category: 'Style',
    title: 'Finding a wig that feels like you',
    excerpt: 'Your best wig is not always the trendiest one. Start with what fits your lifestyle.',
    date: 'Aug 08, 2026',
    image: '/wig8.jpeg',
  },
]